### ISSUE TITLE
Modify Client to run in BOT mode.

### ISSUE THREAD

**Issue by uberlinuxguy** [OpenParsec/openparsec#24]
Running bot clients is very annoying.  Shouldn't be too terrible to move the code to the server... he says without looking at it.

**Comment by uberlinuxguy** [comment]
@CrazySpence  started this and there is a compile option now that went in with 5529830cb41d3141e5b13001fa468c11c12713ad  I want to try to make a command option or .con option to run it all from the same client without special compiles.  This might be something I look at pretty soon since @CrazySpence started the ground work.

**Comment by CrazySpence** [comment]
The client does run in bot mode now with ./parsec -b since last spring
