### ISSUE TITLE
Client dumps keystrokes while flying into the console when opened.

### ISSUE THREAD

**Issue by AbortRetryFail** [OpenParsec/openparsec#39]
This seems like it stems from a change in SDL1.2 -> SDL2 since it's mentioned here: https://wiki.libsdl.org/MigrationGuide#Input

If you're flying around on keyboard control, once you open the console, all of the keystrokes from flying get turned into text input and stuck into the console.

All this does is make spurious chat messages, since it usually doesn't start with a /, but it's still annoying.

**Comment by uberlinuxguy** [comment]
fixed by @AbortRetryFail in 80904e92d84d6f458a77c1397584ecce88e3549c
