### ISSUE TITLE
Ran into an issue building openparsec on opensuse 13.2

### ISSUE THREAD

**Issue by Mirppc** [OpenParsec/openparsec#47]
I was compiling Openparsec on opensuse 13.2 64bit when i ran into the following message during the make command.

~/bin/openparsec/platforms/premake> make -j1
==== Building client (debug32) ====
glew.c
In file included from /usr/include/features.h:402:0,
                 from /usr/include/stdint.h:25,
                 from /usr/lib64/gcc/x86_64-suse-linux/4.8/include/stdint.h:9,
                 from ../../../../src/libraries/glew/glew.h:220,
                 from ../../../../src/libraries/glew/glew.c:32:
/usr/include/gnu/stubs.h:7:27: fatal error: gnu/stubs-32.h: No such file or directory
 # include <gnu/stubs-32.h>
                           ^
compilation terminated.
Makefile:382: recipe for target 'obj/x32/Debug/glew.o' failed
make[1]: *** [obj/x32/Debug/glew.o] Error 1
Makefile:16: recipe for target 'client' failed
make: *** [client] Error 2

**Comment by CrazySpence** [comment]
project only builds as 32bit, you need to use a 32bit dist or have the 32bit libs and headers also installed on your 64bit OS
