### ISSUE TITLE
Domain DNS down and pointing to non function server

### ISSUE THREAD

**Issue by CrazySpence** [OpenParsec/openparsec#48]
-openparsec.com down
-Master server down
-DNS Whois record has unusual data in it, last change was mid June 
-yes i know that took awhile to notice it's summer

**Comment by CrazySpence** [comment]
[2016-07-02 22:20:12] <uberlinuxguy> anyone around?
[2016-07-02 22:22:52] <uberlinuxguy> CrazySpence: When you get a moment, can you email me and let me know if we moved the master server to your server?  I'm also curious if you might want to take over hosting the site.

Both the master and website were already hosted by me for quite some time

**Comment by uberlinuxguy** [comment]
I had to shutdown the server that was hosting website a few months ago. Do you have a place you can host it? I also moved the DNS to Google domain names a little while back too.

**Comment by CrazySpence** [comment]
i was hosting it for ages, when you moved the dns in june that broke it, if you point *.openparsec.com back to 85.119.82.182 you'll see it come back up

**Comment by uberlinuxguy** [comment]
Should be all set. mail still points to my Gmail account, but let me know if you want it to go to your server too.

**Comment by CrazySpence** [comment]
looks good, no that's fine, no one likes email.
