### ISSUE TITLE
Openparsec.com is expiring

### ISSUE THREAD

**Issue by uberlinuxguy** [OpenParsec/openparsec#54]
Openparsec.com is expiring soon. I was not planning on renewing it. If one of the contributors would like to take it over, @CrazySpence I'm looking at you, please let me know. You have until Dec 11th, 2019.

**Comment by CrazySpence** [comment]
Yea ill take it over, what registrar do you use and what's the transfer procedure

**Comment by uberlinuxguy** [comment]
I use Google domains. Can't hardly beat $12 a year... But money is getting tight for me... I will look into the transfer process tomorrow.

**Comment by uberlinuxguy** [comment]
Actually, i just checked and it auto renewed... Thought I told it not to.. oh well... We get another year I guess.

**Comment by uberlinuxguy** [comment]
I think I can share it with you and you can sort of take it over that way

**Comment by CrazySpence** [comment]
Whoops, early renewal? those bastards!

Anyways let me know and i'll take it well before the next one heh

**Comment by uberlinuxguy** [comment]
Do you use Google domains?  If so I can share it with you. You should have my Gmail address. If not, it's the same as my username on here.

**Comment by CrazySpence** [comment]
I can log into google domains because i have a gmail but i do not personally use it my nickname @gmail.com

**Comment by uberlinuxguy** [comment]
It's that time again!  @CrazySpence  I can transfer the domain to your google account or I can transfer it to your registrar of choice.  Let me know. :-)

**Comment by CrazySpence** [comment]
i use GKG.net for my other domains

**Comment by CrazySpence** [comment]
if you generate an auth code and send it to phil@philtopia.com I'll take care of it

**Comment by CrazySpence** [comment]
Auth code accepted and Transfer request submitted

**Comment by CrazySpence** [comment]
No one replied to the confirmation from my Registrar and it cancelled.

**Comment by jhujasonw** [comment]
I looked for a confirmation, didn't see one. I will renew it and we can try again.

**Comment by uberlinuxguy** [comment]
Yup totally forgot about it again this year.  Already renewed it.  Will probably just deal with it for now.

**Comment by CrazySpence** [comment]
lol

**Comment by uberlinuxguy** [comment]
I'm going to close this now... I'm good with the $12 a year for now.... lol
