### ISSUE TITLE
Remote Events don't seem to fire in 64-bit client

### ISSUE THREAD

**Issue by uberlinuxguy** [OpenParsec/openparsec#66]
When connected to a server, RE's don't seem to fire.

**Comment by tribad** [comment]
Is there some better description on the thing so that I can check that and my find the problem?

**Comment by uberlinuxguy** [comment]
Sorry, this was more of a note to myself issue, but if you want to take a stab at it, the issue seems to be that when you collide with power ups, the sound for that powerup doesn't fire and the notification didn't flash on the screen.  I also did not see the power up added to my inventory.  This lead me to believe that the Remote Event code in the Networking code on the client side wasn't firing .  I didn't do much debugging on this other than testing it for a short period of time in enyo.openparsec.com

**Comment by CrazySpence** [comment]
The client isnt registering it, the server is.

You can confirm this easily by picking up energy. Nothing will happen client side but the server will force update your energy. Also works for other powerups, they should appear on the client after the server updates the client.

So the client is sending the server information and receiving it.

What is more accurate is that client side extra collision isn't working properly

**Comment by CrazySpence** [comment]
Did another test of this

Client side collisions are not working at all

Things that wont work:
-Collecting guns
-Collecting extras (ones the server checks will force update your client, missiles, energy, health)
-Going through a star gate
-Shield particle sphere when hitting an enemy (however the target health will update if the server agrees with the hit)
-Teleporters

**Comment by CrazySpence** [comment]
geomv_t	bsphere = MyShip->BoundingSphere;

That is 0 in function void CheckShipExtraCollision(); something tells me the bounding sphere isn't supposed to be 0 but I'm not good enough at this 3d stuff to fix it 

Hopefully that's enough breadcrumbs for someone who can

**Comment by uberlinuxguy** [comment]
I know where this is.  Ill get this one.

**Comment by uberlinuxguy** [comment]
commit 654555ef70470b77f2a6d54f56c9bed917b9de1c seems to have fixed
