### ISSUE TITLE
Solar panel ship extras bug

### ISSUE THREAD

**Issue by CrazySpence** [OpenParsec/openparsec#78]
When using the solar panel ship it constantly announces its getting extras and you get an audible "amazing" repeatedly

Using other ships you do not get this, however if you switch ships mid game you'll get the leftover Queued "amazings"

The Server corrects your inventory constantly while this is happening so you'll see the energy bar go up and down, missiles light up and go grey. etc

**Comment by uberlinuxguy** [comment]
commit 654555ef70470b77f2a6d54f56c9bed917b9de1c seems to have fixed
