### ISSUE TITLE
Segmentation faults

### ISSUE THREAD

**Issue by Vitexus** [OpenParsec/openparsec#82]
Hi, there is several segmentaion fault. I know now about two on strange places:

https://github.com/OpenParsec/openparsec/blob/e2b1e09b277a9c5e2a186bcd3e9c6384cdc98252/src/parsec/sl_msg.cpp#L127

https://github.com/OpenParsec/openparsec/blob/e2b1e09b277a9c5e2a186bcd3e9c6384cdc98252/src/libparsec/obj_odt.cpp#L782

Im using gcc version 10.2.1 20210110 (Debian 10.2.1-6)   

[parsec: ELF 64-bit LSB pie executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=0859cd1a21991fbe00deed674293d50881630ffe, for GNU/Linux 3.2.0, with debug_info, not stripped](https://github.com/OpenParsec/openparsec/files/7610489/parsec.gz)

What can be wrong ?

**Comment by slime73** [comment]
Are you using the `uberlinuxguy/64bit` branch? The main branch doesn't support 64 bit yet.

**Comment by Vitexus** [comment]
@slime73 good to know! Sure i'd for the main.  Please wait a moment for rebuild with branch you recommend.

**Comment by Vitexus** [comment]
@slime73   merge the uberlinuxguy/64bit with my main  =   game start without any problem :smile:  Now i can build my packges 
Thank you!
